import type { Metadata } from "next";
import { Dancing_Script, Jost, Playfair_Display } from "next/font/google";
import { AudioToggle } from "@/components/shared/audio-toggle";
import { GrainOverlay } from "@/components/shared/grain-overlay";
import { Nav } from "@/components/shared/nav";
import "./globals.css";

const playfairDisplay = Playfair_Display({
  style: ["italic"],
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
  weight: "300",
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      className={`${playfairDisplay.variable} ${jost.variable} ${dancingScript.variable} h-full antialiased`}
      lang="en"
    >
      <body className="flex min-h-full flex-col overflow-x-hidden">
        <GrainOverlay />
        <Nav />
        {children}
        <AudioToggle />
      </body>
    </html>
  );
}
